import fs from 'node:fs/promises';
import path from 'node:path';
import {
  renderBulletList,
  renderDocument,
  renderMarkdownTable,
  renderSection,
  type DetectedSignal,
  type DetectedStack,
  type GeneratorContext,
  type GeneratorResult,
} from './base-generator.js';
import { generateAgentsTemplate } from './agents.generator.js';
import { generateClaudeTemplate } from './claude.generator.js';
import { generateSteeringTemplate } from './steering.generator.js';
import { generateCursorDetectCommandTemplate, generateCursorSetupCommandTemplate, generateCursorTemplate } from './cursor.generator.js';
import { recommendEcosystem, selectSimplifiedRecommendation } from './ecosystem-recommender.generator.js';
import type { SimplifiedRecommendation } from '../run-contract.js';

export interface GenerateConfigsOptions {
  detection?: unknown;
  detected?: unknown;
  targetPath?: string;
  targetDir?: string;
  rootDir?: string;
  cwd?: string;
  dryRun?: boolean;
}

export interface RecommendationArtifacts {
  simplified: SimplifiedRecommendation;
  markdown: string;
}

export async function generateConfigs(options: GenerateConfigsOptions = {}): Promise<GeneratorResult[]> {
  const targetRoot = path.resolve(options.targetPath ?? options.targetDir ?? options.rootDir ?? options.cwd ?? process.cwd());
  const detected = normalizeDetectedStack(options.detection ?? options.detected);
  const projectName = path.basename(targetRoot);
  const existingFiles = await listTopLevelFiles(targetRoot);

  const agentsPath = path.join(targetRoot, 'AGENTS.md');
  const claudePath = path.join(targetRoot, 'CLAUDE.md');
  const steeringPath = path.join(targetRoot, 'steering', 'harness-recommendations.md');
  const cursorPath = path.join(targetRoot, '.cursor', 'rules', 'harness.mdc');
  const cursorDetectCommandPath = path.join(targetRoot, '.cursor', 'commands', 'harness-detect.md');
  const cursorSetupCommandPath = path.join(targetRoot, '.cursor', 'commands', 'harness-setup.md');

  const baseContext = {
    projectName,
    projectRoot: targetRoot,
    existingFiles,
    detected,
  };

  const results: GeneratorResult[] = [
    generateAgentsTemplate({
      ...baseContext,
      targetPath: agentsPath,
      existingContent: await readTextIfExists(agentsPath),
    }),
    generateClaudeTemplate({
      ...baseContext,
      targetPath: claudePath,
      existingContent: await readTextIfExists(claudePath),
    }),
    generateSteeringTemplate({
      ...baseContext,
      targetPath: steeringPath,
      existingContent: await readTextIfExists(steeringPath),
    }),
  ];

  if (detected.tools.includes('cursor')) {
    results.push(
      generateCursorTemplate({
        ...baseContext,
        targetPath: cursorPath,
        existingContent: await readTextIfExists(cursorPath),
      }),
      generateCursorDetectCommandTemplate({
        ...baseContext,
        targetPath: cursorDetectCommandPath,
        existingContent: await readTextIfExists(cursorDetectCommandPath),
      }),
      generateCursorSetupCommandTemplate({
        ...baseContext,
        targetPath: cursorSetupCommandPath,
        existingContent: await readTextIfExists(cursorSetupCommandPath),
      }),
    );
  }

  return results;
}

export default generateConfigs;

export async function buildRecommendationArtifacts(options: GenerateConfigsOptions & { fullReportPath?: string } = {}): Promise<RecommendationArtifacts> {
  const targetRoot = path.resolve(options.targetPath ?? options.targetDir ?? options.rootDir ?? options.cwd ?? process.cwd());
  const detected = normalizeDetectedStack(options.detection ?? options.detected);
  const projectName = path.basename(targetRoot);
  const existingFiles = await listTopLevelFiles(targetRoot);
  const context: GeneratorContext = {
    projectName,
    projectRoot: targetRoot,
    targetPath: targetRoot,
    existingFiles,
    detected,
  };
  const recommendation = recommendEcosystem(context);
  const fullReportPath = options.fullReportPath ?? '.harness/runs/<run-id>/recommendations.md';
  return {
    simplified: selectSimplifiedRecommendation(context, recommendation, fullReportPath),
    markdown: renderRecommendationReport(context, recommendation),
  };
}

function renderRecommendationReport(context: GeneratorContext, recommendation = recommendEcosystem(context)): string {
  const rows = recommendation.recommendations.map((item) => [
    item.title,
    item.why,
    item.tips.join('<br>'),
    `confidence ${item.confidence.toFixed(2)}`,
  ]);

  const hookSections = recommendation.recommendations.map((item) => {
    return renderSection(
      `${item.title} Hook`,
      ['```text', item.hookCode, '```'].join('\n'),
    );
  });

  return renderDocument([
    '# AI Tool Recommendations',
    `Generated by Harness from local detection signals for \`${context.projectName ?? 'project'}\`.`,
    renderSection(
      'Recommendation Summary',
      renderBulletList([
        `Ecosystem: ${recommendation.ecosystem}`,
        `Score: ${recommendation.score.toFixed(2)}`,
        `Reason: ${recommendation.reason}`,
      ]),
    ),
    renderSection(
      'Recommended Tools And Hooks',
      renderMarkdownTable(['Recommendation', 'Why', 'Usage Tips', 'Confidence'], rows),
    ),
    ...hookSections,
  ]);
}

export function normalizeDetectedStack(input: unknown): DetectedStack {
  const record = (input && typeof input === 'object' ? input : {}) as Record<string, unknown>;
  const report = (record.report && typeof record.report === 'object' ? record.report : record) as Record<string, unknown>;
  const summary = (report.summary && typeof report.summary === 'object' ? report.summary : {}) as Record<string, unknown>;
  const toolsInput = Array.isArray(record.tools) ? record.tools : [];
  const findings = Array.isArray(report.findings) ? report.findings : [];

  const stackIds = arrayOfStrings(summary.stacks);
  const frameworks = arrayOfStrings(summary.frameworks);
  const commands = arrayOfCommands(record.commands ?? summary.commands);
  const toolNames = toolsInput
    .map((item) => (item && typeof item === 'object' ? String((item as Record<string, unknown>).tool ?? '') : ''))
    .filter(Boolean);

  const evidenceFiles = [
    ...toolsInput.flatMap((item) => {
      if (!item || typeof item !== 'object') return [];
      const evidence = (item as Record<string, unknown>).evidence;
      return Array.isArray(evidence) ? evidence.map(String) : [];
    }),
    ...findings.flatMap((item) => {
      if (!item || typeof item !== 'object') return [];
      const evidence = (item as Record<string, unknown>).evidence;
      return Array.isArray(evidence)
        ? evidence.map((entry) => (entry && typeof entry === 'object' ? String((entry as Record<string, unknown>).path ?? '') : ''))
        : [];
    }),
  ].filter(Boolean);

  const signals: DetectedSignal[] = findings
    .flatMap((item) => {
      if (!item || typeof item !== 'object') return undefined;
      const finding = item as Record<string, unknown>;
      const signal: DetectedSignal = {
        name: String(finding.id ?? finding.label ?? 'unknown'),
        source: String(finding.category ?? 'detection'),
      };
      return signal;
    })
    .filter((item): item is DetectedSignal => Boolean(item));

  return {
    languages: stackIds.flatMap(stackToLanguages),
    runtimes: stackIds.includes('node') ? ['node'] : [],
    packageManagers: detectPackageManagers(evidenceFiles),
    frameworks,
    commands,
    tools: [...new Set(toolNames)],
    files: [...new Set(evidenceFiles)],
    signals,
    notes: [
      summary.repoShape ? `repoShape=${String(summary.repoShape)}` : '',
      Array.isArray(summary.aiTraces) ? `aiTraces=${summary.aiTraces.join(',')}` : '',
    ].filter(Boolean),
  };
}

function stackToLanguages(stack: string): string[] {
  if (stack === 'node') return ['javascript', 'typescript'];
  if (stack === 'python') return ['python'];
  if (stack === 'go') return ['go'];
  if (stack === 'rust') return ['rust'];
  if (stack === 'java') return ['java'];
  return [stack];
}

function detectPackageManagers(files: string[]): string[] {
  const managers = new Set<string>();
  for (const file of files) {
    if (file.endsWith('pnpm-lock.yaml') || file.endsWith('pnpm-workspace.yaml')) managers.add('pnpm');
    if (file.endsWith('yarn.lock')) managers.add('yarn');
    if (file.endsWith('package-lock.json')) managers.add('npm');
    if (file.endsWith('poetry.lock')) managers.add('poetry');
  }
  return [...managers];
}

function arrayOfStrings(value: unknown): string[] {
  return Array.isArray(value) ? value.map(String).filter(Boolean) : [];
}

function arrayOfCommands(value: unknown): Array<{ name: string; command: string; source: string }> {
  if (!Array.isArray(value)) return [];
  return value
    .map((item) => {
      if (!item || typeof item !== 'object') return undefined;
      const record = item as Record<string, unknown>;
      const name = String(record.name ?? '').trim();
      const command = String(record.command ?? '').trim();
      const source = String(record.source ?? '').trim();
      return name && command && source ? { name, command, source } : undefined;
    })
    .filter((item): item is { name: string; command: string; source: string } => Boolean(item));
}

async function readTextIfExists(filePath: string): Promise<string> {
  try {
    return await fs.readFile(filePath, 'utf8');
  } catch {
    return '';
  }
}

async function listTopLevelFiles(root: string): Promise<string[]> {
  try {
    const entries = await fs.readdir(root, { withFileTypes: true });
    return entries.map((entry) => `${entry.name}${entry.isDirectory() ? '/' : ''}`);
  } catch {
    return [];
  }
}
