/**
 * Minimal end-to-end smoke test for the v2 init pipeline.
 *
 * detect → recordPlan → applyFromPlan → verify round-trip.
 * Uses the minimal-repo fixture in a tmpdir so the source tree is untouched.
 */

import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { runInitDetect, runInitRecordPlan, runInitApplyFromPlan } from '../templates/auto-detect/init-pipeline.ts';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const fixtureSrc = path.join(root, 'templates/auto-detect/fixtures/minimal-repo');

const tmpdir = path.join(
  process.platform === 'win32' ? process.env.TEMP || '/tmp' : '/tmp',
  `harness-smoke-init-${crypto.randomBytes(6).toString('hex')}`,
);

try {
  // Copy fixture to tmpdir.
  await fs.cp(fixtureSrc, tmpdir, { recursive: true });

  // Phase 1: detect.
  const detectResult = await runInitDetect(tmpdir);
  console.log(`detect ok  runId=${detectResult.runId}`);

  // Phase 4: record a minimal HRP (one entry for AGENTS.md).
  const testContent = `# AGENTS.md (smoke test)\n\nGenerated by smoke-init.mjs.\n`;
  const recordResult = await runInitRecordPlan({
    targetPath: tmpdir,
    detectRunId: detectResult.runId,
    entries: [
      {
        path: path.join(tmpdir, 'AGENTS.md'),
        action: 'overwrite',
        content: testContent,
        evidenceReason: 'smoke-init: minimal round-trip test entry',
      },
    ],
    skipped: [
      {
        path: path.join(tmpdir, 'CLAUDE.md'),
        reason: 'smoke-init: skip for minimal test',
      },
      {
        path: path.join(tmpdir, 'steering', 'harness-recommendations.md'),
        reason: 'smoke-init: skip for minimal test',
      },
      {
        path: path.join(tmpdir, '.cursor', 'rules', 'harness.mdc'),
        reason: 'smoke-init: no cursor pair in this fixture',
      },
      {
        path: path.join(tmpdir, '.cursor', 'commands', 'harness-init.md'),
        reason: 'smoke-init: no cursor pair in this fixture',
      },
    ],
    summary: 'AGENTS.md | overwrite | evidence: smoke test',
  });
  console.log(`record ok  runId=${recordResult.runId}  entries=${recordResult.entryCount}`);

  // Phase 5: apply from plan.
  const applyResult = await runInitApplyFromPlan(tmpdir, recordResult.runId);
  const { counts, writtenEntries } = applyResult.result;
  console.log(`apply ok   runId=${applyResult.runId}  applied=${counts.applied}  failed=${counts.failed}`);

  // Verify round-trip.
  if (counts.failed !== 0) {
    throw new Error(`Expected 0 failures, got ${counts.failed}`);
  }
  for (const entry of writtenEntries) {
    if (entry.actualSha256 !== entry.intendedSha256) {
      throw new Error(`SHA mismatch for ${entry.path}: ${entry.actualSha256} !== ${entry.intendedSha256}`);
    }
    const diskContent = await fs.readFile(entry.path, 'utf8');
    if (diskContent !== testContent) {
      throw new Error(`Content mismatch for ${entry.path}`);
    }
  }

  console.log('smoke-init ok: detect → record → apply round-trip verified');
} finally {
  await fs.rm(tmpdir, { recursive: true, force: true }).catch(() => {});
}
